### ISSUE TITLE
Solution of #1

### ISSUE THREAD

**Issue by hillyuan** [dariomangoni/MumpsWin#3]
I encounted the same problem of #1 at windows10+ cmake 3.11.2: with BUILD_SHARED_LIBS=OFF, libraries other than libpord.lib and those with capital name are not built. It can be solved after following modification  

For libmpiseq.lib, e.g., modify
---------------------- 
ADD_LIBRARY(libmpiseq STATIC
							${LIBSEQ_HEAD_C}
							${LIBSEQ_HEAD_FORTRAN}
							$<TARGET_OBJECTS:LIBMPISEQ_C>
							$<TARGET_OBJECTS:LIBMPISEQ_FORTRAN>)
--------------------
onto
-------------------
ADD_LIBRARY(libmpiseq STATIC
							${LIBSEQ_SRC_FORTRAN}
						        ${LIBSEQ_HEAD_FORTRAN}
							${LIBSEQ_SRC_C}
					    	        ${LIBSEQ_HEAD_C})
-------------------

I am not quite understand the reason but it works.

**Comment by hillyuan** [comment]
It seems like only fortran obj are linked. Problem still!

**Comment by dariomangoni** [comment]
I'll give a look into this.
Your solution cannot be applied because you are mixing Fortran and C __source__ code.
That cannot be done.

As the MUMPS makefile suggest the steps are the following:
- **compile** Fortran sources into an intermediate object file (namely LIBMPISEQ_FORTRAN)
-  **compile** C sources into an intermediate object file (namely LIBMPISEQ_C)
- **link** objects into the library file (namely libmpiseq.lib)

But I see that there is no libmpiseq.lib output.

libpord on the contrary is not using this approach since it has only C sources, thus no intermediate object files are used to build the library.
It is a known problem that some linkers may not be able to create libraries from object files only... but this shouldn't be the case.

Need some time to fix...

**Comment by dariomangoni** [comment]
Dear hillyuan,
I just pushed [a commit](14b0bc7fdb33b63950ec821daab6daff19a75bbb) that should fix this issue.

Any library that was using the intermediate-objects approach was not actually linking the objects at all.
I successfully built and installed Mumps (ver5.1.2).

I'll wait your OK to close the issue.

**Comment by hillyuan** [comment]
Thanks! I have also solved this problem by adding SET_TARGET_PROPERTIES as LINKER_LANGUAGE FORTRAN, successfully build Mumps 5.1.1 on Windows 10, while you use LINKER_LANGUAGE C. 

By the way, there are some problems which I think you should consider.

1.  It seems that you consider GNU compiler. You may need consider PREFIX "" to avoid name like liblibprod
2.  Compile option -fpp may not works for GNU

3.  It is better to consider the difference between -MD -MDd -MT -MTd.
